name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  matrix:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest # see https://github.com/go-gst/go-gst/issues/64
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      # - name: Downgrade mingw to 11.2.0
      #   if: runner.os == 'Windows'
      #   run: choco install mingw --version 11.2.0 --allow-downgrade
      - name: Setup GStreamer
        id: setup_gstreamer
        uses: blinemedical/setup-gstreamer@v1.4.0
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: build
        shell: bash
        run: |
          packages=$(go list ./...)
          for package in $packages; do
            echo "Building: $package"
            go build $package || exit 1
            echo "Build done: $package"
          done
